### ISSUE TITLE
[solved] I'm not able to make the provided example work...

### ISSUE THREAD

**Issue by trash-anger** [Pegase745/node-gandi#3]
Bonjour Michel, Hi everyone,

I get a little issue using your gandi api wrapper (this is the exact exemple you provides) :
```
var cli = require('node-gandi');
var apikey = 'my-api-key';
var domain = 'insan.fr';
var gandi = new cli(apikey, true);

var callback = function(err, data) {
  if (data[domain] == 'pending') {
    console.log('result is not yet ready')
    setTimeout(function() {
      gandi.call('domain.', [[domain]], callback);
    }, 700)
  }
  else {
    console.dir(data);
  }
}

gandi.call('domain.available', [[domain]], callback );
```

Then I get : 
```
/root/insan/src/first.js:7
  if (data[domain] == 'pending') {
          ^

TypeError: Cannot read property 'insan.fr' of undefined
    at cb (/root/insan/src/first.js:7:11)
    at /root/insan/node_modules/node-gandi/src/gandi.js:113:9
    at /root/insan/node_modules/xmlrpc/lib/client.js:130:9
    at callback (/root/insan/node_modules/xmlrpc/lib/deserializer.js:30:7)
    at Deserializer.onDone (/root/insan/node_modules/xmlrpc/lib/deserializer.js:89:12)
    at emitNone (events.js:67:13)
    at SAXStream.emit (events.js:166:7)
    at Object.SAXStream._parser.onend (/root/insan/node_modules/sax/lib/sax.js:190:10)
    at emit (/root/insan/node_modules/sax/lib/sax.js:624:35)
    at end (/root/insan/node_modules/sax/lib/sax.js:667:5)
```

I'm not very familiar with nodejs yet so this is probably not due to your module but if you can tell me the cause it would be very kind !

**Comment by Pegase745** [comment]
Hi, thanks for the feedback ! Could you please `if (err) throw err;` in order to check why `data` is undefined ?

**Comment by Pegase745** [comment]
I see a first problem with your example
```js
setTimeout(function() {
  gandi.call('domain.available', [[domain]], callback); <-- you forgot the `.available`
}, 700)
```

**Comment by trash-anger** [comment]
Oh yes indeed, but it's present in my current code and the issue was still the same.

Here was the error returned by ``if (err) console.log(err)`` : 
```
{ [Error: XML-RPC fault: Error on object : OBJECT_ACCOUNT (CAUSE_NORIGHT) [Invalid API key]]
  code: 510150,
  faultCode: 510150,
  faultString: 'Error on object : OBJECT_ACCOUNT (CAUSE_NORIGHT) [Invalid API key]' }
```

I was generating my api key from the beta dashboard which seem not be working, so I did it from the v4.

Everything is working now ! Thank you very much ! 👍 💯 🥇

**Comment by Pegase745** [comment]
@trash-anger fyi the apikey generated on beta will be the one to be used in a near future where a new set of v5 apis will be made public. It is normal that it doesn't work on the current xmlrpc api.

**Comment by Pegase745** [comment]
@trash-anger you can already use the v5 apikey on the new livedns API for example, http://doc.livedns.gandi.net/

**Comment by trash-anger** [comment]
Great news !!! Have you an idea about the release date of v5 apis ?

**Comment by Pegase745** [comment]
It's hard to tell, maybe when the front v4 won't be live anymore. It'll be surely announced on https://news.gandi.net/ when it's done.
